name: b128b282-dee7-44a7-bc21-f1fd21452a83
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - pystac-client
  - odc-stac
  - jupyter
  - geopandas
  - rioxarray
  - rasterstats
  - hvplot
  - datashader
  - scikit-learn
  - geoviews
